package Timekeeping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class Day_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("^(31|30|[012]\\d|\\d)$");
  }
}
