package Timekeeping.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Month {
  January("January", "1"),
  February("February", "2"),
  March("March", "3"),
  April("April", "4"),
  May("May", "5"),
  June("June", "6"),
  Jule("Jule", "7"),
  August("August", "8"),
  September("September", "9"),
  October("October", "10"),
  November("November", "11"),
  December("December", "12");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private Month(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<Month> getConstants() {
    List<Month> list = ListSequence.fromList(new LinkedList<Month>());
    ListSequence.fromList(list).addElement(Month.January);
    ListSequence.fromList(list).addElement(Month.February);
    ListSequence.fromList(list).addElement(Month.March);
    ListSequence.fromList(list).addElement(Month.April);
    ListSequence.fromList(list).addElement(Month.May);
    ListSequence.fromList(list).addElement(Month.June);
    ListSequence.fromList(list).addElement(Month.Jule);
    ListSequence.fromList(list).addElement(Month.August);
    ListSequence.fromList(list).addElement(Month.September);
    ListSequence.fromList(list).addElement(Month.October);
    ListSequence.fromList(list).addElement(Month.November);
    ListSequence.fromList(list).addElement(Month.December);
    return list;
  }
  public static Month getDefault() {
    return Month.January;
  }
  public static Month parseValue(String value) {
    if (value == null) {
      return Month.getDefault();
    }
    if (value.equals(Month.January.getValueAsString())) {
      return Month.January;
    }
    if (value.equals(Month.February.getValueAsString())) {
      return Month.February;
    }
    if (value.equals(Month.March.getValueAsString())) {
      return Month.March;
    }
    if (value.equals(Month.April.getValueAsString())) {
      return Month.April;
    }
    if (value.equals(Month.May.getValueAsString())) {
      return Month.May;
    }
    if (value.equals(Month.June.getValueAsString())) {
      return Month.June;
    }
    if (value.equals(Month.Jule.getValueAsString())) {
      return Month.Jule;
    }
    if (value.equals(Month.August.getValueAsString())) {
      return Month.August;
    }
    if (value.equals(Month.September.getValueAsString())) {
      return Month.September;
    }
    if (value.equals(Month.October.getValueAsString())) {
      return Month.October;
    }
    if (value.equals(Month.November.getValueAsString())) {
      return Month.November;
    }
    if (value.equals(Month.December.getValueAsString())) {
      return Month.December;
    }
    return Month.getDefault();
  }
}
