package Timekeeping.editor;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface TableDataProvider {
  Object getColumn(SNode n, int i);
  void setColumn(SNode n, int i, Object o);
  boolean validColumnValue(SNode n, int i, Object o);
  int getColumnCount();
  String[] getColumnNames();
}
